### ISSUE TITLE
error will appear in every player login

### ISSUE THREAD

**Issue by qq9906898** [esx-framework/esx_whitelistEnhanced#24]
hello~~i am a Taiwanese 
my english is very bad :((
who can help me solve this problem?
I am trying to start "https://github.com/ESX-Org/esx_whitelistEnhanced" and make sure my system ESX version is 1.1.0
EssentialMode version is 6.1.0
It will appear in every player login
But still there is a problem!!:((
![unknown](https://user-images.githubusercontent.com/49778649/56413150-16a69b00-62b9-11e9-87b7-511ac1b129d0.png)

**Comment by lvp11** [comment]
Same issue.
Got any fixes?

**Comment by LySoon** [comment]
İ got same thing too..

**Comment by Monster125** [comment]
i want to fix

**Comment by C0kkie** [comment]
https://github.com/ESX-Org/esx_whitelistEnhanced/pull/26

Should help you
